### ISSUE TITLE
为什么Wiki的文章是直接从第二篇开始的

### ISSUE THREAD

**Issue by KnightJoker** [geeeeeeeeek/git-recipes#11]
文章写得挺好的，谢谢分享
不过第一篇呢，第一篇呢，第一篇呢~
强迫症患者= =+

**Comment by houkensjtu** [comment]
@KnightJoker 其实。。
https://github.com/geeeeeeeeek/git-recipes/blob/master/sources/%E6%9E%9C%E5%A3%B3%E4%B8%AD%E7%9A%84Git.md

**Comment by geeeeeeeeek** [comment]
@KnightJoker 因为第一章内容比较基础，没什么兴趣翻译。@houkensjtu之前翻过一篇，我过会放到wiki里去。

BTW，我最近在翻译O'reilly的动物书《Git团队协作》，等到出版了你可以关注下哈哈，里面讲的更详细
