### ISSUE TITLE
git hook可以自定义文件名吗？

### ISSUE THREAD

**Issue by zwwtj2014** [geeeeeeeeek/git-recipes#12]
git hooks文件夹里的文件名是确定的吗？还是说我们可以自定义文件然后通过配置来在某个时间点来触发特定的文件？
如果不能自定义文件，是不是意味着多个功能的话要在一个文件里来写？或者通过函数的概念分到多个文件，但是还是只有一个特定的入口文件？

**Comment by geeeeeeeeek** [comment]
git hook 的种类是确定的，相当于一个 lambda 函数，允许你提供特定事件的回调函数。这只是一个入口，hook 脚本就是普通的 python/shell 脚本，所以分多个文件应该没问题（虽然我没试过）。
