### ISSUE TITLE
补充GitLab工作流

### ISSUE THREAD

**Issue by seasonxuan** [geeeeeeeeek/git-recipes#14]
除了wiki里的4个工作流,还有GitLab工作流,可以参考下.阮一峰的博客
[Git 工作流程](http://www.ruanyifeng.com/blog/2015/12/git-workflow.html)

**Comment by geeeeeeeeek** [comment]
其实和阮一峰讲的分法有些不同，他说的GitHub工作流和GitLab工作流在我看来没什么差别。可以供大家参考。

**Comment by justjavac** [comment]
upsteam first
