### ISSUE TITLE
疑似错误：wiki中git revert解释有误

### ISSUE THREAD

**Issue by jasonleft** [geeeeeeeeek/git-recipes#17]
wiki 5.2 代码回滚：Reset、Checkout、Revert的选择

在checkout节有以下文字：

> 如果你缓存并且提交了checkout的文件，它具备将某个文件回撤到之前版本的效果。注意它撤销了这个文件后面所有的更改，而git revert 命令只撤销某个特定提交的更改。

这句话：

> 注意它撤销了这个文件后面所有的更改，而git revert 命令只撤销某个特定提交的更改。

我试了下，git revert直接是恢复到指定的版本，那个指定的提交之后的提交的修改的内容都被撤销，按照你翻译的意思是说只撤销了那个指定的提交的那次的更新，那个提交之后的提交修改的内容还会保存，我觉得你这样翻译是不对的，你看呢？

**Comment by geeeeeeeeek** [comment]
原文如此。

根据 [Git 官方文档](https://git-scm.com/docs/git-revert#_description)：
> Given one or more existing commits, revert the changes that the related patches introduce, and record some new commits that record them.

**Comment by LitoMore** [comment]
Fixed. Closing.
