### ISSUE TITLE
The typo in Wiki

### ISSUE THREAD

**Issue by Howld** [geeeeeeeeek/git-recipes#25]
Link:
https://github.com/geeeeeeeeek/git-recipes/wiki/3.3-%E5%88%9B%E5%BB%BAPull-Request

<pre>
栗子
下面的🌰演示了如何将pull request用在Fork工作流中。

所有的活动都在这个pull request里之间追踪。

Issue:
1. 栗子 => 例子， 🌰 => 例子
2. remove "之间"
</pre>

**Comment by zhulianhua** [comment]
Link:
https://github.com/geeeeeeeeek/git-recipes/wiki/3.4-%E4%BD%BF%E7%94%A8%E5%88%86%E6%94%AF#%E5%88%9B%E5%BB%BA%E5%88%86%E6%94%AF

注意，这只会 *创建* 一个新的分支。要开始在上面添加提交，你需要用 `git checkout` 来选中这个分支，然后使用标准的 `git addh` 和 `git commit` 命令。

Issue:
`git addh` => `git add`

**Comment by LitoMore** [comment]
@zhulianhua Thanks.

**Comment by LitoMore** [comment]
🌰 并非作者的 typo，详见 #21
