### ISSUE TITLE
好文啊 已经被git push -f 坑过了

### ISSUE THREAD

**Issue by SakuraZhang** [geeeeeeeeek/git-recipes#3]
使用git checkout 然后rebase  然后提交的时候本地有修改 结果无法push 加了-f 结果就悲剧了 至今都不知道为何代码被覆盖T_T

**Comment by geeeeeeeeek** [comment]
有时候我也会用-f把中央仓库的代码滚回去，但前提是没有别人在这个分支上...你说的本地有修改无法push没有看懂..

**Comment by SakuraZhang** [comment]
就是本地仓库里面有某个文件修改过了 提示需要commit 才能push 啊
