### ISSUE TITLE
代码合并：Merge、Rebase 的选择这一节貌似有笔误，不确定，新手提问

### ISSUE THREAD

**Issue by Xiyor** [geeeeeeeeek/git-recipes#37]
第一个，Rebase小节里的应该是将master分支并入feature分支吧
第二个，Rebase小节里的图（Brand New Commit）貌似少了一个变基节点

**Comment by LitoMore** [comment]
> 第一个，Rebase 小节里的应该是将 master 分支并入 feature 分支吧

见原文 [Merging vs. Rebasing](https://www.atlassian.com/git/tutorials/merging-vs-rebasing) 中的 The Rebase Option

```
"You can rebase the feature branch onto master branch."
```

> 第二个，Rebase 小节里的图（Brand New Commit）貌似少了一个变基节点

图片没有错误。`Brand New Commit` 不是图片的名称而是注解，图片名称在图片的上方 `Rebasing the feature branch onto master`。

**Comment by LitoMore** [comment]
Closing.
