### ISSUE TITLE
疑似错误：Reset、Checkout、Revert 的选择

### ISSUE THREAD

**Issue by snovey** [geeeeeeeeek/git-recipes#39]
在之前的文章：[2.5 检出之前的提交](https://github.com/geeeeeeeeek/git-recipes/wiki/2.5-检出之前的提交) 中，有这样一段话：
>`git checkout <commit> <file>`
>查看文件之前的版本。它将工作目录中的 <file> 文件变成 <commit> 中那个文件的拷贝，并将它加入缓存区。

然而在这篇文章：[5.2 代码回滚：Reset、Checkout、Revert 的选择](https://github.com/geeeeeeeeek/git-recipes/wiki/5.2-代码回滚：Reset、Checkout、Revert-的选择) 中，是这样说的：
>Checkout 一个文件和带文件路径 git reset 非常像，除了它更改的是工作目录而不是缓存区。不像提交层面的 checkout 命令，它不会移动 HEAD 引用，也就是你不会切换到别的分支上去。

实际上应该是 `git checkout <commit> <file>` 同时修改了工作区与暂存区

**Comment by 0x04C2** [comment]
我理解的 `git checkout <commit> <pathspec>` 是通过 `git read-tree` 底层命令从 `<commit object>` 中取出 `<tree object>`，并放到 `<index>` 也就是我们说的暂存区，最后通过 `git checkout-index` 把 `<tree objdect>` 取出文件放到工作区中。 所以你的理解是对的 @snovey 

Reference: [LINK](https://stackoverflow.com/questions/22534877/a-basic-example-of-the-read-tree-command-usage)

FYI @geeeeeeeeek @LitoMore

**Comment by LitoMore** [comment]
[原文](https://www.atlassian.com/git/tutorials/resetting-checking-out-and-reverting)如下：

> Checking out a file is similar to using git reset with a file path, except it updates the working directory instead of the stage.

**Comment by snovey** [comment]
@0x04C2 谢谢你的支持，我并不懂那么多，是通过实践发现的……
@LitoMore 应当遵从正确的答案，而不是原文，不是么？

**Comment by 0x04C2** [comment]
应该遵从正确答案，我发信给atlassian公司了，看看他们怎么回复

**Comment by xsung** [comment]
@snovey 我测试过了，
> git checkout HEAD foo.py 等同于舍弃 foo.py 没有缓存的更改

这句话有问题。以上操作是 同时修改了工作区与暂存区。
@geeeeeeeeek 作者为什么不更改一下呢

**Comment by LitoMore** [comment]
抱歉，上面我少引用了一句话，重点在后面粗体字的描述：

> Checking out a file is similar to using git reset with a file path, except it updates the working directory instead of the stage. **Unlike the commit-level version of this command, this does not move the HEAD reference, which means that you won’t switch branches.**

原文没有错，其实是翻译错了，原文中重点指出的是两者在 HEAD reference 处的差异，而翻译作者理解成了在对比 working directory 和 stage 状态变化的差异。

这条 issue 会在近期修正。感谢各位 :) @snovey @0x04C2 @xu-song

**Comment by xu-song** [comment]
@LitoMore 大神，能帮我review以下这个图不？
https://gist.github.com/xu-song/f01af17d15e791f1ebc5894b8cf83922
