### ISSUE TITLE
[3.3 创建 Pull Request] 配图错误

### ISSUE THREAD

**Issue by toogoo** [geeeeeeeeek/git-recipes#43]
> 下图展示的是将0492wzl/WeChatLuckyMoney(源仓库)的stable(源分支)合并到geeeeeeeeek/WeChatLuckyMoney(目标仓库)的stable(目标分支)。
 
而配图却是将geeeeeeeeek/WeChatLuckyMoney(源仓库)的stable(源分支)合并到0492wzl/WeChatLuckyMoney(目标仓库)的stable(目标分支)。

**Comment by LitoMore** [comment]
感谢，配图的确错了，左边是 `base` 右边是 `compare`，图片我会在近期纠正

**Comment by LitoMore** [comment]
![image](https://user-images.githubusercontent.com/8186898/36071353-e3aa9852-0f47-11e8-911d-dddd35de2694.png)

应该像这样。

**Comment by LitoMore** [comment]
Fixed. Closing.
