### ISSUE TITLE
为什么木有关于分支概念的介绍？

### ISSUE THREAD

**Issue by sourcemars** [geeeeeeeeek/git-recipes#5]
很不错的一系列文档，但是让我感到比较奇怪的是对于分支概念并没有明确的介绍，而是直接在文档里面使用，这是否会对初学者造成一定的困扰？

**Comment by geeeeeeeeek** [comment]
分支的概念在第三篇，还没有翻译好。第二篇主要是单分支上的操作。

**Comment by xirong** [comment]
@geeeeeeeeek  :+1:  翻译的挺好的 ， 我在 [my-git](https://github.com/xirong/my-git) 中把你的这篇收藏进来了，详细log [#add recipes](https://github.com/xirong/my-git/commit/9adbccf026ae8d71739e8cf2e11d195480cb61b5?short_path=0730bb7#diff-0730bb7c2e8f9ea2438b52e419dd86c9)

**Comment by geeeeeeeeek** [comment]
@xirong 谢谢。不知您是否能够内推阿里/蚂蚁金服学期间实习？前端方向，我在上海。

**Comment by xirong** [comment]
@geeeeeeeeek 可以的，把你的想法、想从事哪方面开发以及简历发我邮件 `ixirong.liu@gmail.com`，邮箱详细沟通下。

**Comment by geeeeeeeeek** [comment]
@xirong 不好意思，邮件刚刚发过去。前段时间项目发布通知太多漏掉了这一条……
