### ISSUE TITLE
图片挂了

### ISSUE THREAD

**Issue by songjhh** [geeeeeeeeek/git-recipes#51]
2.6 回滚错误的修改 里面的图片挂了

**Comment by fangasvsass** [comment]
meger和rebase的图也挂了

**Comment by qhhuang** [comment]
meger和rebase的图也挂了 +1

**Comment by 1ffree** [comment]
+1 好多图片挂了，极大影响阅读体验。

**Comment by x122536638** [comment]
+1 很多图挂了

**Comment by LitoMore** [comment]
PRs welcome :)

**Comment by xiazidong** [comment]
【5.2 代码回滚：Reset、Checkout、Revert 的选择】
图片挂掉了

**Comment by genkagen** [comment]
https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by aermin** [comment]
已star  希望修复一下图片

**Comment by 2er7** [comment]
看起来是原文的图片全都发生了变更，这边的图片应该是全都挂掉了

**Comment by LitoMore** [comment]
我实在是太忙，欢迎大家提 pull request，谢谢

**Comment by LitoMore** [comment]
Closing with #62 #63
