### ISSUE TITLE
把hotfix分支reset到HEAD~2的图片没有了

### ISSUE THREAD

**Issue by zengjuchen** [geeeeeeeeek/git-recipes#70]
https://camo.githubusercontent.com/3d55df040cb530482894661b35212b83ff4e5e14/68747470733a2f2f7777772e61746c61737369616e2e636f6d2f6769742f696d616765732f7475746f7269616c732f616476616e6365642f726573657474696e672d636865636b696e672d6f75742d616e642d726576657274696e672f30322e737667

找不到资源

**Comment by kevinfszu** [comment]
期望尽快修复这个问题，拜托了
