### ISSUE TITLE
图片挂了

### ISSUE THREAD

**Issue by nobut** [geeeeeeeeek/git-recipes#71]
好多章节的图片挂了

**Comment by 2er7** [comment]
#68

> ∠( ᐛ 」∠)＿ Wiki 中的文档没更新，先看仓库的吧：[代码回滚：Reset、Checkout、Revert 的选择](https://github.com/geeeeeeeeek/git-recipes/blob/master/sources/5.2-%E5%9B%9E%E6%BB%9A%E5%91%BD%E4%BB%A4Reset%E3%80%81Checkout%E3%80%81Revert%E8%BE%A8%E6%9E%90.md)


如果是仓库中的图片，请给出具体的章节 or 提 PR
