### ISSUE TITLE
图片无法显示

### ISSUE THREAD

**Issue by PegasusWang** [geeeeeeeeek/git-recipes#74]
https://github.com/geeeeeeeeek/git-recipes/wiki/5.1-%E4%BB%A3%E7%A0%81%E5%90%88%E5%B9%B6%EF%BC%9AMerge%E3%80%81Rebase-%E7%9A%84%E9%80%89%E6%8B%A9

这个页面下的图片无法显示，能否考虑使用 github 的图片上传

**Comment by 2er7** [comment]
看看最近关闭的 Issues 吧 🤪

> > ∠( ᐛ 」∠)＿ Wiki 中的文档没更新，先看仓库的吧：[代码合并：Merge、Rebase 的选择](https://github.com/geeeeeeeeek/git-recipes/blob/master/sources/5.1-%E4%BB%A3%E7%A0%81%E5%90%88%E5%B9%B6Merge%E8%BF%98%E6%98%AFRebase.md)
> 
> 如果是仓库中的图片，请给出具体的章节 or 提 PR

**Comment by geeeeeeeeek** [comment]
我正在更新这些章节，更新后就修复了。

**Comment by zg9uagfv** [comment]
2.6 回滚错误的修改 里面的图片都看不到 @geeeeeeeeek
