### ISSUE TITLE
教程中部分图片无法显示

### ISSUE THREAD

**Issue by kevinfszu** [geeeeeeeeek/git-recipes#76]
“[常见工作流程](https://github.com/geeeeeeeeek/git-recipes/wiki/3.5-%E5%B8%B8%E8%A7%81%E5%B7%A5%E4%BD%9C%E6%B5%81%E6%AF%94%E8%BE%83)”

**Comment by 2er7** [comment]
#68 
可以先看仓库中的 [常见工作流程](https://github.com/geeeeeeeeek/git-recipes/blob/master/sources/3.5-%E5%B8%B8%E8%A7%81%E5%B7%A5%E4%BD%9C%E6%B5%81%E6%AF%94%E8%BE%83.md)

**Comment by kevinfszu** [comment]
我看了一下你给的链接，部分图片回复正常，但还是有部分图片无法显示：[常见工作流程](https://github.com/geeeeeeeeek/git-recipes/blob/master/sources/3.5-%E5%B8%B8%E8%A7%81%E5%B7%A5%E4%BD%9C%E6%B5%81%E6%AF%94%E8%BE%83.md#mary-%E5%AE%8C%E6%88%90%E4%BA%86%E5%A5%B9%E7%9A%84%E5%8A%9F%E8%83%BD)

**Comment by geeeeeeeeek** [comment]
`第2篇 从零搭建本地代码仓库` 全部修订完了，今晚校对完会推送到 master 分支。其他章节随后更新。

**Comment by drinksong** [comment]
> `第2篇 从零搭建本地代码仓库` 全部修订完了，今晚校对完会推送到 master 分支。其他章节随后更新。

还是有很多图片是挂的（2019-1-9）

**Comment by wb-chenlong** [comment]
@geeeeeeeeek 是否可以考虑将图片也存放到该项目下，然后 .md 中进行引用？但是不知道这么多图片，仓库大小是否允许上传。

**Comment by Teakowa** [comment]
> @geeeeeeeeek 是否可以考虑将图片也存放到该项目下，然后 .md 中进行引用？但是不知道这么多图片，仓库大小是否允许上传。

图片也没有多大的，上传不是什么问题。

我也建议在仓库中保存图片并引用，可以保证阅读体验。

**Comment by banjin** [comment]
可以按照文档进行操作验证

**Comment by tangwenixng** [comment]
仍然有很多图片挂了

**Comment by SenierLink** [comment]
第二篇的图片我一个都没看到，似乎都挂完了。

**Comment by WM-CH** [comment]
+1...

**Comment by zhongjiajie** [comment]
https://github.com/geeeeeeeeek/git-recipes/wiki/5.1-%E4%BB%A3%E7%A0%81%E5%90%88%E5%B9%B6%EF%BC%9AMerge%E3%80%81Rebase-%E7%9A%84%E9%80%89%E6%8B%A9

图片挂了,强烈建议将图片也放到git中进行管理

**Comment by tddschn** [comment]
Same here

**Comment by buppter** [comment]
wiki里好多的图都挂了

**Comment by joluzhu96** [comment]
还是很多图挂了 难受呀
