### ISSUE TITLE
关于版权问题

### ISSUE THREAD

**Issue by huangjianke** [geeeeeeeeek/git-recipes#84]
您好，是这样的，日前个人开源了一款GitHub小程序客户端，开源地址：[https://github.com/huangjianke/Gitter](https://github.com/huangjianke/Gitter)，希望将您这个Git教程作为一个模块集成到小程序中，让想学习Git的程序员朋友多一个途径，我会在教程内署名来源和作者信息，您看是否可以呢？期待您的答复，感谢。

**Comment by geeeeeeeeek** [comment]
OK没问题。

**Comment by huangjianke** [comment]
@geeeeeeeeek 好的，感谢
