### ISSUE TITLE
文中图片不能显示

### ISSUE THREAD

**Issue by foreverwang** [geeeeeeeeek/git-recipes#91]
比如这一篇 图片都不能访问
https://github.com/geeeeeeeeek/git-recipes/wiki/5.2-%E4%BB%A3%E7%A0%81%E5%9B%9E%E6%BB%9A%EF%BC%9AReset%E3%80%81Checkout%E3%80%81Revert-%E7%9A%84%E9%80%89%E6%8B%A9

**Comment by LitoMore** [comment]
PRs welcome.

**Comment by smartsl** [comment]
貌似源代码md文件里的图片是好的，但wiki里看不到

**Comment by LitoMore** [comment]
Related to https://github.com/geeeeeeeeek/git-recipes/issues/55.
請以代碼庫中的內容為準，Wiki 即將關閉。
